# **`Notebook_ML_classification_Titanic_Ahmed_Matter`**

Project Showcase: Titanic Survival Prediction: An End-to-End ML Benchmarking Pipeline

**First : Data Connection , EDA , preprocess**

In [ ]:
#Connect to gdrive

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#import lib

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from google.colab import files

In [ ]:
#read dataset
train_df = pd.read_csv('/content/drive/MyDrive/train_Taitanic.csv')
test_df = pd.read_csv('/content/drive/MyDrive/test_Taitanic.csv')

In [ ]:
train_df.head(10)

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S
5            6         0       3  ...   8.4583   NaN         Q
6            7         0       1  ...  51.8625   E46         S
7            8         0       3  ...  21.0750   NaN         S
8            9         1       3  ...  11.1333   NaN         S
9           10         1       2  ...  30.0708   NaN         C

[10 rows x 12 columns]

In [ ]:
test_df.head(10)

   PassengerId  Pclass  ... Cabin Embarked
0          892       3  ...   NaN        Q
1          893       3  ...   NaN        S
2          894       2  ...   NaN        Q
3          895       3  ...   NaN        S
4          896       3  ...   NaN        S
5          897       3  ...   NaN        S
6          898       3  ...   NaN        Q
7          899       2  ...   NaN        S
8          900       3  ...   NaN        C
9          901       3  ...   NaN        S

[10 rows x 11 columns]

In [ ]:
#shape of data
print(f'test data shape is: {test_df.shape} train data shape is {train_df.shape}')

test data shape is: (418, 11) train data shape is (891, 12)

In [ ]:
#train data all cols info
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
#train data all cols null
train_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
#test data all cols info
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB

In [ ]:
#tet data all cols null
test_df.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
#type of data

print(f'test data shape is:\n {test_df.dtypes} \n \n \n train data shape is:\n {train_df.dtypes}')

test data shape is:
 PassengerId      int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object


 train data shape is:
 PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
#data cleaning

columns_to_remove_train = ['PassengerId', 'Name', 'Ticket', 'Cabin']
columns_to_remove_test = ['Name', 'Ticket', 'Cabin']

age_median = train_df['Age'].median()
fare_median = train_df['Fare'].median()

train_df = train_df.drop(columns=columns_to_remove_train, axis=1)
test_df = test_df.drop(columns=columns_to_remove_test, axis=1)


train_df['Age'] = train_df['Age'].fillna(age_median)
test_df['Age'] = test_df['Age'].fillna(age_median)

train_df['Fare'] = train_df['Fare'].fillna(fare_median)
test_df['Fare'] = test_df['Fare'].fillna(fare_median)

train_df.dropna(subset=['Embarked'], inplace=True)
test_df.dropna(subset=['Embarked'], inplace=True)

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  889 non-null    int64
 1   Pclass    889 non-null    int64
 2   Sex       889 non-null    object
 3   Age       889 non-null    float64
 4   SibSp     889 non-null    int64
 5   Parch     889 non-null    int64
 6   Fare      889 non-null    float64
 7   Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 62.5+ KB

In [ ]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Sex          418 non-null    object
 3   Age          418 non-null    float64
 4   SibSp        418 non-null    int64
 5   Parch        418 non-null    int64
 6   Fare         418 non-null    float64
 7   Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 26.3+ KB

In [ ]:
train_df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female  28.0      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[889 rows x 8 columns]

In [ ]:
test_df

     PassengerId  Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0            892       3    male  34.5      0      0    7.8292        Q
1            893       3  female  47.0      1      0    7.0000        S
2            894       2    male  62.0      0      0    9.6875        Q
3            895       3    male  27.0      0      0    8.6625        S
4            896       3  female  22.0      1      1   12.2875        S
..           ...     ...     ...   ...    ...    ...       ...      ...
413         1305       3    male  28.0      0      0    8.0500        S
414         1306       1  female  39.0      0      0  108.9000        C
415         1307       3    male  38.5      0      0    7.2500        S
416         1308       3    male  28.0      0      0    8.0500        S
417         1309       3    male  28.0      1      1   22.3583        C

[418 rows x 8 columns]

**Second : Encoding & Scaling**

In [ ]:
#Encoding

#Encode Sex Col

gender_mapping = {'male': 0, 'female': 1}


train_df['Sex'] = train_df['Sex'].map(gender_mapping)
test_df['Sex'] = test_df['Sex'].map(gender_mapping)

encoder = OneHotEncoder(sparse_output=False)
#Encode embarked Col
embarked_encoded_train = encoder.fit_transform(train_df[['Embarked']])
embarked_encoded_test = encoder.transform(test_df[['Embarked']])


encoded_columns = encoder.get_feature_names_out(['Embarked'])

train_embarked_df = pd.DataFrame(embarked_encoded_train, columns=encoded_columns, index=train_df.index)
test_embarked_df = pd.DataFrame(embarked_encoded_test, columns=encoded_columns, index=test_df.index)


train_df = pd.concat([train_df.drop(columns=['Embarked']), train_embarked_df], axis=1)
test_df = pd.concat([test_df.drop(columns=['Embarked']), test_embarked_df], axis=1)

#Encode Pclass Col
pclass_encoded_train = encoder.fit_transform(train_df[['Pclass']])
pclass_encoded_test = encoder.transform(test_df[['Pclass']])

encoded_columns = encoder.get_feature_names_out(['Pclass'])

train_pclass_df = pd.DataFrame(pclass_encoded_train, columns=encoded_columns, index=train_df.index)
test_pclass_df = pd.DataFrame(pclass_encoded_test, columns=encoded_columns, index=test_df.index)

train_df = pd.concat([train_df.drop(columns=['Pclass']), train_pclass_df], axis=1)
test_df = pd.concat([test_df.drop(columns=['Pclass']), test_pclass_df], axis=1)


#Feature Engineering by adding 2cols familysize and is alone

train_df['FamilySize'] = train_df['SibSp'] + train_df['Parch'] + 1
test_df['FamilySize'] = test_df['SibSp'] + test_df['Parch'] + 1


train_df['IsAlone'] = (train_df['FamilySize'] == 1).astype(int)
test_df['IsAlone'] = (test_df['FamilySize'] == 1).astype(int)



#Drop columns SibSp ,Parch

columns_to_drop = ['SibSp', 'Parch']

train_df = train_df.drop(columns=columns_to_drop, axis=1)
test_df = test_df.drop(columns=columns_to_drop, axis=1)

In [ ]:
#Scaling

scaler = StandardScaler()

numerical_cols = ['Age', 'Fare']

train_df[numerical_cols] = scaler.fit_transform(train_df[numerical_cols])

test_df[numerical_cols] = scaler.transform(test_df[numerical_cols])

**show data after encoding and scaling**

In [ ]:
train_df

     Survived  Sex       Age      Fare  ...  Pclass_2  Pclass_3  FamilySize  IsAlone
0           0    0 -0.563674 -0.500240  ...       0.0       1.0           2        0
1           1    1  0.669217  0.788947  ...       0.0       0.0           2        0
2           1    1 -0.255451 -0.486650  ...       0.0       1.0           1        1
3           1    1  0.438050  0.422861  ...       0.0       0.0           2        0
4           0    0  0.438050 -0.484133  ...       0.0       1.0           1        1
..        ...  ...       ...       ...  ...       ...       ...         ...      ...
886         0    0 -0.178396 -0.384475  ...       1.0       0.0           1        1
887         1    1 -0.794841 -0.042213  ...       0.0       0.0           1        1
888         0    1 -0.101340 -0.174084  ...       0.0       1.0           4        0
889         1    0 -0.255451 -0.042213  ...       0.0       0.0           1        1
890         0    0  0.206883 -0.490173  ...       0.0       1.0           1        1

[889 rows x 12 columns]

In [ ]:
test_df

     PassengerId  Sex       Age  ...  Pclass_3  FamilySize  IsAlone
0            892    0  0.399522  ...       1.0           1        1
1            893    1  1.362718  ...       1.0           2        0
2            894    0  2.518553  ...       0.0           1        1
3            895    0 -0.178396  ...       1.0           1        1
4            896    1 -0.563674  ...       1.0           3        0
..           ...  ...       ...  ...       ...         ...      ...
413         1305    0 -0.101340  ...       1.0           1        1
414         1306    1  0.746273  ...       0.0           1        1
415         1307    0  0.707745  ...       1.0           1        1
416         1308    0 -0.101340  ...       1.0           1        1
417         1309    0 -0.101340  ...       1.0           3        0

[418 rows x 12 columns]

**Third : Train & Test Models**

In [ ]:
y = train_df['Survived']
x = train_df.drop(columns=['Survived'])
X_train, X_val, y_train, y_val = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:

modelRF = RandomForestClassifier(n_estimators=400, random_state=42)

modelRF.fit(X_train, y_train)

y_predRF = modelRF.predict(X_val)
accuracyRF = accuracy_score(y_val, y_pred)

print(f"\n {accuracyRF * 100:.2f}%")

print(classification_report(y_val, y_pred))

 76.40%
              precision    recall  f1-score   support

           0       0.84      0.76      0.80       109
           1       0.67      0.77      0.72        69

    accuracy                           0.76       178
   macro avg       0.75      0.76      0.76       178
weighted avg       0.77      0.76      0.77       178

In [ ]:
log_model = LogisticRegression(max_iter=1000, random_state=42)


log_model.fit(X_train, y_train)

y_pred_log = log_model.predict(X_val)
accuracy_log = accuracy_score(y_val, y_pred_log)

print(f"\n {accuracy_log * 100:.2f}%")

print(classification_report(y_val, y_pred_log))

 80.34%
              precision    recall  f1-score   support

           0       0.84      0.83      0.84       109
           1       0.74      0.75      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.79      0.79       178
weighted avg       0.80      0.80      0.80       178

In [ ]:
tree_model = DecisionTreeClassifier(max_depth=5, random_state=42)
tree_model.fit(X_train, y_train)

y_pred_tree = tree_model.predict(X_val)
accuracy_tree = accuracy_score(y_val, y_pred_tree)
print(f": {accuracy_tree * 100:.2f}%")
print(classification_report(y_val, y_pred_tree))

: 81.46%
              precision    recall  f1-score   support

           0       0.84      0.86      0.85       109
           1       0.77      0.74      0.76        69

    accuracy                           0.81       178
   macro avg       0.81      0.80      0.80       178
weighted avg       0.81      0.81      0.81       178

In [ ]:
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)

y_pred_nb = nb_model.predict(X_val)
accuracy_nb = accuracy_score(y_val, y_pred_nb)
print(f": {accuracy_nb * 100:.2f}%")
print(classification_report(y_val, y_pred_nb))

: 76.97%
              precision    recall  f1-score   support

           0       0.82      0.80      0.81       109
           1       0.69      0.72      0.71        69

    accuracy                           0.77       178
   macro avg       0.76      0.76      0.76       178
weighted avg       0.77      0.77      0.77       178

In [ ]:
svm_model = SVC(kernel='rbf', random_state=42)
svm_model.fit(X_train, y_train)


y_pred_svm = svm_model.predict(X_val)
accuracy_svm = accuracy_score(y_val, y_pred_svm)
print(f": {accuracy_svm * 100:.2f}%")
print(classification_report(y_val, y_pred_svm))

: 82.02%
              precision    recall  f1-score   support

           0       0.86      0.84      0.85       109
           1       0.76      0.78      0.77        69

    accuracy                           0.82       178
   macro avg       0.81      0.81      0.81       178
weighted avg       0.82      0.82      0.82       178

In [ ]:
gb_model = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)
gb_model.fit(X_train, y_train)


y_pred_gb = gb_model.predict(X_val)
accuracy_gb = accuracy_score(y_val, y_pred_gb)
print(f": {accuracy_gb * 100:.2f}%")
print(classification_report(y_val, y_pred_gb))

: 80.90%
              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.75      0.77      0.76        69

    accuracy                           0.81       178
   macro avg       0.80      0.80      0.80       178
weighted avg       0.81      0.81      0.81       178

**Fourth : Select The Best Model**

In [ ]:

results = pd.DataFrame({
    'Model': ['Random Forest', 'Logistic Regression', 'Decision Tree', 'Naive Bayes', 'SVM', 'Gradient Boosting'],
    'Accuracy': [
        accuracyRF * 100,
        accuracy_log * 100,
        accuracy_tree * 100,
        accuracy_nb * 100,
        accuracy_svm * 100,
        accuracy_gb * 100
    ]
})

results = results.sort_values(by='Accuracy', ascending=False).reset_index(drop=True)

print(results)

                 Model   Accuracy
0                  SVM  82.022472
1        Decision Tree  81.460674
2    Gradient Boosting  80.898876
3  Logistic Regression  80.337079
4          Naive Bayes  76.966292
5        Random Forest  76.404494

**Fifth : Prediction**

In [ ]:

Predictions = svm_model.predict(test_df[X.columns])

submission = pd.DataFrame({
    'PassengerId': test_df['PassengerId'],
    'Survived': Predictions
})


submission.to_csv('titanic_svm_predictions.csv', index=False)

submission

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [ ]:
#Optional run to download the file
#files.download('titanic_svm_predictions.csv')